# Generated by Django 3.2.23 on 2023-12-16 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=18, verbose_name='Название темы')),
            ],
        ),
        migrations.CreateModel(
            name='Pomodor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(default='🍅', max_length=1, verbose_name='Иконка')),
                ('minute_intensive', models.PositiveIntegerField(verbose_name='Время сосредоточения')),
                ('datetime_field', models.DateTimeField(verbose_name='Дата и время создание')),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pomodors', to='timer.theme')),
            ],
        ),
    ]
