# Generated by Django 4.2.6 on 2023-12-22 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(default='#9da1aa', max_length=7, verbose_name='Цвет')),
            ],
        ),
        migrations.AlterModelOptions(
            name='pomodor',
            options={'verbose_name': 'Помидор', 'verbose_name_plural': 'Помидоры'},
        ),
        migrations.AlterModelOptions(
            name='theme',
            options={'verbose_name': 'Тема', 'verbose_name_plural': 'Темы'},
        ),
        migrations.AlterField(
            model_name='theme',
            name='name',
            field=models.CharField(max_length=64, verbose_name='Название темы'),
        ),
    ]
