# Generated by Django 3.2.23 on 2023-12-23 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timer', '0004_auto_20231223_2325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pomodorconfig',
            name='theme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='configuration', to='timer.theme', verbose_name='Выбранная тема'),
        ),
    ]
