# Generated by Django 4.2.6 on 2023-12-26 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timer', '0005_alter_pomodorconfig_theme'),
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название мелодии')),
                ('url', models.URLField(verbose_name='Расположение мелодии')),
            ],
        ),
        migrations.AddField(
            model_name='pomodorconfig',
            name='time_relax',
            field=models.PositiveIntegerField(default=5, verbose_name='Время отдыха'),
        ),
        migrations.AlterField(
            model_name='pomodorconfig',
            name='theme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='configuration', to='timer.theme', verbose_name='Выбранная тема'),
        ),
        migrations.AddField(
            model_name='pomodorconfig',
            name='song_intensive',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='config_intensive', to='timer.song'),
        ),
        migrations.AddField(
            model_name='pomodorconfig',
            name='song_relax',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='config_relax', to='timer.song'),
        ),
    ]
