# Generated by Django 3.2.23 on 2023-12-28 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timer', '0008_auto_20231228_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config',
            name='song_intensive',
            field=models.CharField(default='/pomodoro/melody/matrix.mp3', max_length=100, verbose_name='URL к мелодии'),
        ),
        migrations.AlterField(
            model_name='config',
            name='song_relax',
            field=models.CharField(default='/pomodoro/melody/matrix.mp3', max_length=100, verbose_name='URL к мелодии'),
        ),
    ]
