# Generated by Django 3.2.23 on 2024-01-09 09:35

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timer', '0011_auto_20231228_2326'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(default='🏖️', max_length=1, verbose_name='Иконка')),
                ('minute_rest', models.PositiveIntegerField(verbose_name='Время сосредоточения')),
                ('datetime_field', models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='Дата и время создание')),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rest', to='timer.theme')),
            ],
            options={
                'verbose_name': 'Отдых',
                'verbose_name_plural': 'Отдыхи',
            },
        ),
    ]
