# Generated by Django 3.2.23 on 2024-01-09 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timer', '0012_rest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Дата сессии')),
            ],
        ),
        migrations.AddField(
            model_name='pomodor',
            name='session',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='timer.session'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rest',
            name='session',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='timer.session'),
            preserve_default=False,
        ),
    ]
