# Generated by Django 3.2.23 on 2024-01-09 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timer', '0013_auto_20240109_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='theme',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='timer.theme'),
            preserve_default=False,
        ),
    ]
