# Generated by Django 3.2.23 on 2024-01-09 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timer', '0014_session_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pomodor',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pomodors', to='timer.session'),
        ),
        migrations.AlterField(
            model_name='rest',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rest', to='timer.session'),
        ),
    ]
